feat:Do stage1 task
AndVikVin/JetTestApplication pull request #1
Opened 2019-02-13 18:35 UTC by AndVikVin

2019-02-14 16:35 UTC, HelgaListopad requested changes

2019-02-14 16:35 UTC, HelgaListopad commented on index.html
> +	<script type="text/javascript" src="./codebase/webix.js"></script>
`codebase` помечена в gitignore (что правильно).
Но в проекте на гитхабе вебикса фактически нет - перенеси его в какую-то другую папку (чтобы путь отличался от от myapp.js) и добавь в репозиторий.

2019-02-14 16:35 UTC, HelgaListopad commented on index.html
> +	<link rel="stylesheet" type="text/css" href="./codebase/webix.css">
То же самое - файла сейчас нет в проекте

2019-02-14 16:35 UTC, HelgaListopad commented on sources/models/activities.js
> +		$change:(obj)=>{
Если не знадан `init`, `change` сработает и вместо него тоже, так что `init` можно смело убирать.

2019-02-14 16:35 UTC, HelgaListopad commented on sources/models/activities.js
> +			const dateFormat =  webix.Date.strToDate("%d-%m-%Y %H:%i");
Каждый из этих методов срабатывает для отдельно взятого айтема, так что один и тот же парсер создаётся множество раз. Лучше вынести "за скобки" - как отдельную константу вне коллекции.

2019-02-14 16:35 UTC, HelgaListopad commented on sources/models/activities.js
> +			const dateFormat =  webix.Date.strToDate("%d-%m-%Y %H:%i");
Так как у тебя в коллекции лежит Date (это хорошо и правильно), а на сервер должна уходить строка, нужен `dateToStr` с форматом, указанным в самом конце Developer's guide (год-месяц-день время).

Сейчас оно работает по большей части случайно.)
Date проходит через парсер `strToDate` (который преобразовывает строку, а с датой ничего делать не станет), остаётся без изменений и уже при отправке на сервер преобразовывается в правильную строку через внутреннюю магию Webix - [parseFormat](https://docs.webix.com/api__i18n_parseformat_other.html), который зависит от текущей локали. 
Такой зависимости (тем более случайной) быть не должно, т.к. если локаль поменять - сервер уже не получит строку нужного формата.

2019-02-14 16:35 UTC, HelgaListopad commented on sources/models/activities.js
> +			const dateFormat =  webix.Date.strToDate("%d-%m-%Y %H:%i");
И в целом, чтобы как-то отлавливать такие ситуацииб в методах scheme можно добавить проверку на `typeof obj.DueDate`

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/ContactInfo.js
> +			currentItem.Value = statuses.getItem(values.StatusID).Value;
Не помешает проверка, есть ли вообще StatusID

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/ContactInfo.js
> +			const id = view.$scope.getParam("id");
Благодаря стрелочной функции, здесь `view.$scope` - то же, что и `this`

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/ContactInfo.js
> +			view.getChildViews()[0].parse(currentItem);
Обращения по `getChildViews` весьма ненадёжные (поменешь структуру layout - и нулевой чайлд может быть уже другим). 
Джет позволяет задавать вьюшкам [свойство](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/referencing-views#5-referencing-webix-widgets) `localId`, для того, чтобы вызывать компоненты от класса как `this.$$("some_id")` - это самое удобное решение.
Ещё один вариант, который лучше использовать в крайнем случае - метод [queryView](https://docs.webix.com/api__link__ui.view_queryview.html).

На всякий случай - от глобальных `id` в приложенях лучше по возможности отказаться, т.к. это недопустимый вариант для переипользуемых модулей.

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/activity.js
> +				{id:"DueDate",header:["Due Date",{content:"datepickerFilter"}], adjust:"data",format:webix.Date.dateToStr("%d-%m-%Y %H:%i"), sort:"date",fillspace:true},
Для datepickerFilter хорошо было бы включить таймпикер - по умолчанию он выставляет время 00:00, так что фильтрация получается очень привередливой.
```
{ content:"datepickerFilter", inputConfig:{ timepicker:true }}
```
Или заменить его на фильтр dateRange

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/activity.js
> +					});
Добавь `return false;` и здесь - иначе без webix.confirm может вылезти нехорошая ошибка, если бы у тебя был включён select или обрабатывался onItemClick.

Клики обрабатываются примерно так
onClick на класс в строке -> onItemClick -> обработка select

Поэтому после удаления айтема дальнейшую обработку клика из onClick нужно блокировать.

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/activity.js
> +			view.queryView("datatable").sync(activities);
localId был бы уместнее

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/activity.js
> +		this.PopupWinEdit = this.ui(PopupWinEdit);
В идеале окно должно быть одно - нет смысла инитить два одинаковых.  
В showPopup можно передать, например, параметр (можно и целый data item, как сейчас), и в зависимости от которого можно просто менять лэйблы add/editю
У тебя это и так уже почти реализовано, и действие save/add в форме уже обрабатывается правильно.

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/contacts.js
> +		view.queryView("list").parse(contactsCollServ);
здесь и ниже - localId

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/popupWin.js
> +					{view:"checkbox", label:"Complited"},
Не хватает `checkValue:"Open", unCheckValue:"Close"`

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/popupWin.js
> +										activities.updateItem(id,newValues);
Из newValues перед апдейтом можно было бы удалить Date и Time - насколько я могу судить, они не нужны вне формы.

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/top.js
> +		header.define("template",currentItem["value"]);
Вместо define лучше было бы использовать метод [setHTML](https://docs.webix.com/api__ui.template_sethtml.html)

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/top.js
> +					this.app.show("/top/" + id);
Эта логика уже реализована в [menu plugin](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/plugins#menu-plugin), который позволяет избавиться от urlChange ниже. 
Если использовать его, в onAfterSelect останется только поменять заголовок страницы (template)

2019-02-14 16:35 UTC, HelgaListopad commented on sources/views/top.js
> +		const header = view.queryView("template");
И всё-таки localId

2019-02-15 16:44 UTC, Zwillinge commented on sources/models/activities.js
> +		$change:(obj)=>{
а разве DueDate может быть строкой при изменениях?  приложение внутри должно работать с датами как Date object-ами, поэтому парсить строки надо только на $init  (+ поправить обработку даты в окне. )

2019-02-15 16:55 UTC, Zwillinge commented on sources/models/activities.js
> +			const dateFormat =  webix.Date.strToDate("%d-%m-%Y %H:%i");
И придерживаться правила - на входе строки преобразовали в объекты, при сохранении - наоборот. Внутри приложение (за исключение темплейтов виджетов) работает исключительно с объектами.

2019-02-15 16:58 UTC, Zwillinge commented on sources/views/activity.js
> +			view.queryView("datatable").sync(activities);
а зачем здесь then? синхронизировать данные можно и не дожидаясь резолва промиса.

2019-02-15 17:12 UTC, Zwillinge requested changes

2019-02-15 17:12 UTC, Zwillinge commented on sources/models/contacts.js
> +		$init:(obj)=>{
если мы отредактируем имя и фамилию контакта (stage 2), value останется таким же. здесь имеет смысл на поменять на $change

2019-02-15 17:12 UTC, Zwillinge commented on sources/views/ContactInfo.js
> +			const id = this.getParam("id");
а если нет параметра в url-е? здесь как и в модуле контактов надо проверять наличие такого элемента в коллекции, иначе я могу сейчас написать что угодно в адресной строке, а этот модуль сгенерирует ошибку

2019-02-15 17:12 UTC, Zwillinge commented on sources/views/ContactInfo.js
> +			const values = contactsCollServ.getItem(id);
`values` здесь абсолютно лишняя переменная. 
можно сразу получить копию и с ней работать  

`currentItem = webix.copy(contactsCollServ.getItem(id));`

2019-02-15 17:12 UTC, Zwillinge commented on sources/views/popupWin.js
> +								const formatDate = webix.Date.dateToStr("%d-%m-%Y");
нет смысла сначала форматировать date object, зачем склеивать эти строки, а затем снова парсить их в date object. собирать время-дату нужно непосредственно через Date,
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/setHours

т.е. получаем дату из левого дейтпикера, часы и минуты из правого и комбинируем это всё в DueDate

2019-02-15 17:12 UTC, Zwillinge commented on sources/views/popupWin.js
> +								this.$$("form").clear();
по клику на обе кнопки мы делаем одно и то то же: чистим форму, валидацию и прячем окно. надо вынести повторяющийся код либо в:

* метод  класса PopupWin  и вызывать его из  save и cancel
* либо обрабатывать событие onHide у окна, внутри которого чистить форму и валидацию

2019-02-17 09:29 UTC, Zwillinge requested changes
Андрей, большая просьба - не нужно резолвить открытые замечания, это для ревьюера. 
Мы должны иметь возможность зайти в review и проверить правки по актуальным вопросам, а не вспоминать, что же тут еще не так.

2019-02-17 09:29 UTC, Zwillinge commented on sources/views/popupWin.js
> +					{view:"checkbox", label:"Complited", checkValue:"Open", unCheckValue:"Close"},
это поле ничего не делает, а должно редактировать поле State.

2019-02-17 09:59 UTC, merged